# Generated by Django 5.1.3 on 2024-12-11 17:30

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarFarmTimeseries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(
                        interval="10 minutes"
                    ),
                ),
                ("node_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "solar_irradiance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Solar irradiance in W/m²",
                        max_digits=7,
                    ),
                ),
                (
                    "power_output",
                    models.DecimalField(
                        decimal_places=2, help_text="Power output in kW", max_digits=10
                    ),
                ),
                (
                    "module_temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Module temperature in °C",
                        max_digits=5,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries_data",
                        to="farms.solarfarm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solar Farm Time Series Data",
                "verbose_name_plural": "Solar Farm Time Series Data",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["time", "node_id", "farm_id"],
                        name="timeseries__time_f9ff41_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("time", "node_id", "farm_id"),
                        name="timeseries_solarfarmtimeseries_unique_time_station",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WindFarmTimeseries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(
                        interval="10 minutes"
                    ),
                ),
                ("node_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_power_min",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Minimum active power in kW",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "active_power_max",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Maximum active power in kW",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "active_power_mean",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mean active power in kW",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "energy_accumulated",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total accumulated energy in kWh",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "energy_accumulated_export",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total exported energy in kWh",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "energy_accumulated_import",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Total imported energy in kWh",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "wind_speed_mean",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mean wind speed in m/s",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "wind_speed_stddev",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard deviation of wind speed",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "wind_direction_mean",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mean wind direction in degrees",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "wind_direction_stddev",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Standard deviation of wind direction",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "power_reduction_time",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Time spent in power reduction mode",
                        max_digits=10,
                        null=True,
                    ),
                ),
                (
                    "measurement_wind_speed_mean",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mean measured wind speed in m/s",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "measurement_wind_direction_mean",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Mean measured wind direction in degrees",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "farm",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries_data",
                        to="farms.windfarm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wind Farm Time Series Data",
                "verbose_name_plural": "Wind Farm Time Series Data",
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["time", "node_id", "farm_id"],
                        name="timeseries__time_f219d2_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("time", "node_id", "farm_id"),
                        name="timeseries_windfarmtimeseries_unique_time_station",
                    )
                ],
            },
        ),
    ]
