# Generated by Django 5.1.3 on 2024-12-06 11:02

import django.db.models.deletion
import timescale.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolarFarmTimeseries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "solar_irradiance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Solar irradiance in W/m²",
                        max_digits=7,
                    ),
                ),
                (
                    "power_output",
                    models.DecimalField(
                        decimal_places=2, help_text="Power output in kW", max_digits=10
                    ),
                ),
                (
                    "module_temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Module temperature in °C",
                        max_digits=5,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries_data",
                        to="farms.solarfarm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Solar Farm Time Series Data",
                "verbose_name_plural": "Solar Farm Time Series Data",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["time"], name="timeseries__time_6a44dd_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("time", "station_id"),
                        name="timeseries_solarfarmtimeseries_unique_time_station",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WindFarmTimeseries",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "time",
                    timescale.db.models.fields.TimescaleDateTimeField(interval="1 day"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "wind_speed",
                    models.DecimalField(
                        decimal_places=2, help_text="Wind speed in m/s", max_digits=5
                    ),
                ),
                (
                    "wind_direction",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Wind direction in degrees",
                        max_digits=5,
                    ),
                ),
                (
                    "power_output",
                    models.DecimalField(
                        decimal_places=2, help_text="Power output in kW", max_digits=10
                    ),
                ),
                (
                    "temperature",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Ambient temperature in °C",
                        max_digits=5,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="timeseries_data",
                        to="farms.windfarm",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wind Farm Time Series Data",
                "verbose_name_plural": "Wind Farm Time Series Data",
                "abstract": False,
                "indexes": [
                    models.Index(fields=["time"], name="timeseries__time_a8b2fd_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("time", "station_id"),
                        name="timeseries_windfarmtimeseries_unique_time_station",
                    )
                ],
            },
        ),
    ]
