# Generated by Django 5.1.3 on 2024-12-12 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("file", "File"), ("database", "Database")],
                        max_length=10,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="imports/")),
                (
                    "db_connection",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("is_continuous", models.BooleanField(default=False)),
                (
                    "interval_minutes",
                    models.PositiveIntegerField(
                        default=10,
                        help_text="Interval for continuous imports in minutes",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "solar_farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="farms.solarfarm",
                    ),
                ),
                (
                    "target_model",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "wind_farm",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="import_jobs",
                        to="farms.windfarm",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ColumnMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_column",
                    models.CharField(
                        help_text="Column name from the source data", max_length=100
                    ),
                ),
                (
                    "target_field",
                    models.CharField(
                        help_text="Field name in the target model", max_length=100
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mappings",
                        to="data_import.importjob",
                    ),
                ),
            ],
        ),
    ]
