# Generated by Django 5.1.3 on 2024-12-02 17:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("registration_number", models.CharField(max_length=100, unique=True)),
                ("address", models.TextField()),
                ("contact_email", models.EmailField(max_length=254)),
                ("contact_phone", models.CharField(max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Companies",
            },
        ),
        migrations.CreateModel(
            name="SolarFarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2, help_text="Area in hectares", max_digits=10
                    ),
                ),
                ("commissioned_date", models.DateField(blank=True, null=True)),
                (
                    "nominal_power",
                    models.DecimalField(
                        decimal_places=2, help_text="Nominal power in MW", max_digits=10
                    ),
                ),
                ("operational_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("panel_type", models.CharField(max_length=100)),
                ("number_of_panels", models.PositiveIntegerField()),
                ("panel_manufacturer", models.CharField(max_length=100)),
                ("panel_model", models.CharField(max_length=100)),
                (
                    "tracking_system",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the panels have a solar tracking system",
                    ),
                ),
                (
                    "tilt_angle",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Panel tilt angle in degrees",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "azimuth_angle",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Panel azimuth angle in degrees",
                        max_digits=4,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(360),
                        ],
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="solar_farms",
                        to="farms.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WindFarm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("location", models.CharField(max_length=200)),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                (
                    "total_area",
                    models.DecimalField(
                        decimal_places=2, help_text="Area in hectares", max_digits=10
                    ),
                ),
                ("commissioned_date", models.DateField(blank=True, null=True)),
                (
                    "nominal_power",
                    models.DecimalField(
                        decimal_places=2, help_text="Nominal power in MW", max_digits=10
                    ),
                ),
                ("operational_status", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "hub_height",
                    models.DecimalField(
                        decimal_places=2, help_text="Hub height in meters", max_digits=6
                    ),
                ),
                (
                    "rotor_diameter",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rotor diameter in meters",
                        max_digits=6,
                    ),
                ),
                (
                    "cut_in_wind_speed",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Cut-in wind speed in m/s",
                        max_digits=4,
                    ),
                ),
                (
                    "cut_out_wind_speed",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Cut-out wind speed in m/s",
                        max_digits=4,
                    ),
                ),
                ("number_of_turbines", models.PositiveIntegerField()),
                ("turbine_manufacturer", models.CharField(max_length=100)),
                ("turbine_model", models.CharField(max_length=100)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wind_farms",
                        to="farms.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
