# Generated by Django 5.1.3 on 2024-12-02 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="solarfarm",
            name="panel_manufacturer",
        ),
        migrations.RemoveField(
            model_name="solarfarm",
            name="panel_type",
        ),
        migrations.RemoveField(
            model_name="windfarm",
            name="cut_in_wind_speed",
        ),
        migrations.RemoveField(
            model_name="windfarm",
            name="cut_out_wind_speed",
        ),
        migrations.RemoveField(
            model_name="windfarm",
            name="hub_height",
        ),
        migrations.RemoveField(
            model_name="windfarm",
            name="rotor_diameter",
        ),
        migrations.RemoveField(
            model_name="windfarm",
            name="turbine_manufacturer",
        ),
        migrations.AddField(
            model_name="solarfarm",
            name="array_configuration",
            field=models.TextField(
                blank=True,
                help_text="Description of panel array configuration and spacing",
            ),
        ),
        migrations.AddField(
            model_name="windfarm",
            name="average_wind_speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Average wind speed at hub height in m/s",
                max_digits=4,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="windfarm",
            name="layout_description",
            field=models.TextField(
                blank=True, help_text="Description of turbine layout and spacing"
            ),
        ),
        migrations.CreateModel(
            name="SolarPanelModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "technology_type",
                    models.CharField(
                        help_text="e.g., Monocrystalline, Polycrystalline, Thin-film",
                        max_length=50,
                    ),
                ),
                (
                    "nominal_power",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Nominal power in Watts",
                        max_digits=6,
                    ),
                ),
                (
                    "efficiency",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Panel efficiency percentage",
                        max_digits=4,
                    ),
                ),
                (
                    "length",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Length in millimeters",
                        max_digits=6,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        decimal_places=2, help_text="Width in millimeters", max_digits=6
                    ),
                ),
                (
                    "depth",
                    models.DecimalField(
                        decimal_places=2, help_text="Depth in millimeters", max_digits=5
                    ),
                ),
                (
                    "weight",
                    models.DecimalField(
                        decimal_places=2, help_text="Weight in kilograms", max_digits=6
                    ),
                ),
                (
                    "temperature_coefficient",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Temperature coefficient in %/°C",
                        max_digits=4,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Solar Panel Model",
                "verbose_name_plural": "Solar Panel Models",
                "unique_together": {("manufacturer", "model_name")},
            },
        ),
        migrations.AlterField(
            model_name="solarfarm",
            name="panel_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="farms.solarpanelmodel"
            ),
        ),
        migrations.CreateModel(
            name="WindTurbineModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("manufacturer", models.CharField(max_length=100)),
                ("model_name", models.CharField(max_length=100)),
                (
                    "rated_power",
                    models.DecimalField(
                        decimal_places=2, help_text="Rated power in MW", max_digits=8
                    ),
                ),
                (
                    "rotor_diameter",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Rotor diameter in meters",
                        max_digits=6,
                    ),
                ),
                (
                    "hub_height",
                    models.DecimalField(
                        decimal_places=2, help_text="Hub height in meters", max_digits=6
                    ),
                ),
                (
                    "cut_in_speed",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Cut-in wind speed in m/s",
                        max_digits=4,
                    ),
                ),
                (
                    "cut_out_speed",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Cut-out wind speed in m/s",
                        max_digits=4,
                    ),
                ),
                (
                    "rated_wind_speed",
                    models.DecimalField(
                        decimal_places=1,
                        help_text="Rated wind speed in m/s",
                        max_digits=4,
                    ),
                ),
                (
                    "power_curve",
                    models.JSONField(
                        blank=True,
                        help_text="Power curve data points as JSON",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Wind Turbine Model",
                "verbose_name_plural": "Wind Turbine Models",
                "unique_together": {("manufacturer", "model_name")},
            },
        ),
        migrations.AlterField(
            model_name="windfarm",
            name="turbine_model",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="farms.windturbinemodel"
            ),
        ),
    ]
