# Generated by Django 5.1.3 on 2024-12-02 18:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("farms", "0002_remove_solarfarm_panel_manufacturer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="windturbinemodel",
            name="generator_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("DFIG", "Doubly-Fed Induction Generator"),
                    ("PMSG", "Permanent Magnet Synchronous Generator"),
                    ("SCIG", "Squirrel Cage Induction Generator"),
                    ("WRIG", "Wound Rotor Induction Generator"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="generator_voltage",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Generator voltage in V",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="grid_frequency",
            field=models.CharField(
                default="50/60", help_text="Grid frequency in Hz", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="installation_year",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Year of first installation",
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(1980),
                    django.core.validators.MaxValueValidator(2100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="max_rotor_speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Maximum rotor speed in rpm",
                max_digits=5,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="nacelle_weight",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Nacelle weight in tonnes",
                max_digits=8,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="number_of_blades",
            field=models.PositiveIntegerField(
                default=3,
                validators=[
                    django.core.validators.MinValueValidator(2),
                    django.core.validators.MaxValueValidator(4),
                ],
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="offshore_suitable",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="onshore_suitable",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="survival_wind_speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Maximum survival wind speed in m/s",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(30),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="swept_area",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Swept area in m²",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="tower_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("STEEL", "Steel Tube"),
                    ("HYBRID", "Hybrid"),
                    ("CONCRETE", "Concrete"),
                    ("LATTICE", "Lattice"),
                    ("OTHER", "Other"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="windturbinemodel",
            name="wind_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("IA", "IEC IA"),
                    ("IB", "IEC IB"),
                    ("IC", "IEC IC"),
                    ("IIA", "IEC IIA"),
                    ("IIB", "IEC IIB"),
                    ("IIC", "IEC IIC"),
                    ("IIIA", "IEC IIIA"),
                    ("IIIB", "IEC IIIB"),
                    ("IIIC", "IEC IIIC"),
                    ("S", "IEC S (Special)"),
                ],
                help_text="IEC Wind Class",
                max_length=4,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="windturbinemodel",
            name="cut_in_speed",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Cut-in wind speed in m/s",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="windturbinemodel",
            name="cut_out_speed",
            field=models.DecimalField(
                decimal_places=1,
                help_text="Cut-out wind speed in m/s",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(40),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="windturbinemodel",
            name="hub_height",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Hub height in meters",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="windturbinemodel",
            name="power_curve",
            field=models.JSONField(
                blank=True,
                help_text="Power curve data points as JSON: {'wind_speeds': [], 'power_output': []}",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="windturbinemodel",
            name="rated_power",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Rated power in kW",
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="windturbinemodel",
            name="rated_wind_speed",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                help_text="Rated wind speed in m/s",
                max_digits=4,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(5),
                    django.core.validators.MaxValueValidator(30),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="windturbinemodel",
            name="rotor_diameter",
            field=models.DecimalField(
                decimal_places=2,
                help_text="Rotor diameter in meters",
                max_digits=6,
                validators=[
                    django.core.validators.MinValueValidator(20),
                    django.core.validators.MaxValueValidator(300),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="windturbinemodel",
            index=models.Index(
                fields=["manufacturer", "model_name"],
                name="farms_windt_manufac_bad7c3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="windturbinemodel",
            index=models.Index(
                fields=["rated_power"], name="farms_windt_rated_p_3c34ac_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="windturbinemodel",
            index=models.Index(
                fields=["rotor_diameter"], name="farms_windt_rotor_d_540883_idx"
            ),
        ),
    ]
